name: poisson-regression
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=2.2.*
  - pandas
  - scikit-learn
  - joblib
  - matplotlib
  - jupyter
  - pytest
  - econml
  - scikit-survival
  - black
  - scipy
  - pip
  - pip:
    - dowhy
    - econml
 